version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bauruServico-web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bauru2971415_servicosbauru
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../banco.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
